name: Close Stale Issues
on:
  schedule:
    - cron: '30 8 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been automatically marked as stale due to inactivity and will be closed in 7 days if no further activity occurs.'
          close-issue-message: 'This issue was closed due to inactivity. Please reopen if you still encounter this problem or have more information to add.'
          days-before-issue-stale: 0
          day-before-issue-closed: 1
          days-before-stale: 999
          days-before-close: 999
          stale-issue-label: 'stale'
          exempt-issue-labels: 'do not stale, needs response'
